spring:
  application:
    name: springbootwebtutorial

  datasource:
#    url: jdbc:postgresql://localhost:5432/springprofile
    url: jdbc:postgresql://spring-profile-db.cpsw4os68ng7.ap-southeast-2.rds.amazonaws.com:5432/springprofile
    username: postgres
    password: postgres-1
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: /spring-profile
  port: 8082

my:
  variable: global

#master username - postgres
#Password in aws db - postgres-1
